### ISSUE TITLE
缺少开源协议

### ISSUE THREAD

**Issue by idanran** [wikipedia-zh/imc#16]
建议CC0

**Comment by Frederisk** [comment]
根惹坝，全文版嗄壳榫者各自所有，K非自由版唷

Rowe Wilson Frederisk Holme
________________________________
寄件者: idanran ***@***.***>
寄件日期: Wednesday, December 14, 2022 12:09:53 AM
收件者: wikipedia-zh/imc ***@***.***>
副本: Subscribed ***@***.***>
主旨: [wikipedia-zh/imc] 缺少开源协议 (Issue #16)


建议CC0

―

**Comment by idanran** [comment]
> 根據先前討論，全文版權目前為編寫者各自所有，並非自由版權。 Rowe Wilson Frederisk Holme
> […](#)
> ________________________________ 寄件者: idanran ***@***.***> 寄件日期: Wednesday, December 14, 2022 12:09:53 AM 收件者: wikipedia-zh/imc ***@***.***> 副本: Subscribed ***@***.***> 主旨: [wikipedia-zh/imc] 缺少开源协议 (Issue #16) 建议CC0 ― Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwikipedia-zh%2Fimc%2Fissues%2F16&data=05%7C01%7C%7Ce1c643bdaccb4917703908dadd2478d8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638065445978883603%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=UhNnJQnITB3U4axhMzBFm5sp%2FITUIrEIkxURk7Og9AE%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHDUTKUYPA36ZATJAVIU3VLWNCNVDANCNFSM6AAAAAAS5MPJI4&data=05%7C01%7C%7Ce1c643bdaccb4917703908dadd2478d8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638065445978883603%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KI5Q4ZNZ6Z9kEQBtoO%2FBT8CVdTFQ25c95F28fUHZJSg%3D&reserved=0>. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

期待未来能成为自由版权
