### ISSUE TITLE
是否考虑提供简体中文版本

### ISSUE THREAD

**Issue by Linisdjxm** [wikipedia-zh/imc#17]
由于版权问题，无法自行翻译为简体中文并发布。维护者是否考虑提供简体中文版本？

**Comment by Da-ze** [comment]
因中文維基百科用戶絕大多數皆可閱讀二文，暫無意願提供簡體中文，請使用考慮 Google Translate 服務（e.g. https://wikipedia--zh-github-io.translate.goog/imc/?_x_tr_sl=zh-TW&_x_tr_tl=zh-CN ）。
